services:
  mariadb:
    build: ./requirements/mariadb
    container_name : mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql



volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mthetcha/data/mariadb
